package kr.kyeoungwoon.upms.global.apiPayload.enums;

public enum DomainType {
  JWT,
  CHALLENGER,
  SCHOOL,
  CHAPTER,
  CHAPTER_SCHOOL,
  CHAPTER_ADMIN,
  INFRA_S3,
  PROJECT,
  PROJECT_MEMBER,
  PROJECT_TO,
  PROJECT_APPLICATION,
  PROJECT_APPLICATION_FORM,
  PROJECT_APPLICATION_RESPONSE,
  PROJECT_MATCHING_ROUND,
  TEST
}
